apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration

mirror:
  platform:
    channels:
      - name: stable-4.18
    architectures:
      - amd64

  operators:
    - catalog: registry.redhat.io/redhat/community-operator-index:v4.18
      packages:
        - name: nfs-csi-driver-operator
          channels:
            - name: stable

