apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  platform:
    architectures:
      - amd64
    channels:
      - name: stable-4.18
        minVersion: 4.18.30
        maxVersion: 4.18.30
        shortestPath: true
        type: ocp
  additionalImages:
    - name: registry.redhat.io/ubi8/ubi:latest
    - name: registry.redhat.io/ubi9/ubi:latest
    - name: registry.redhat.io/openshift4/ose-cli:latest
    - name: registry.redhat.io/openshift4/ose-deployer:latest
    - name: registry.redhat.io/rhel8/support-tools:latest
    - name: registry.redhat.io/rhel9/support-tools:latest
