apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration

storageConfig:
  registry:
    imageURL: registry.cloud.lab:8443/mirror/oc-mirror-metadata
    skipTLS: false   # set false ONLY if registry uses trusted CA

mirror:
  platform:
    architectures:
      - x86_64
    channels: 
      - name: stable-4.18
        type: ocp
        minVersion: "4.18.30"
        maxVersion: "4.18.30"
        shortestPath: true
    graph: true

  additionalImages:
    - name: registry.redhat.io/ubi8/ubi:latest
    - name: registry.redhat.io/ubi9/ubi:latest
    - name: registry.redhat.io/openshift4/ose-cli:latest
    - name: registry.redhat.io/openshift4/ose-deployer:latest
    - name: registry.redhat.io/rhel8/support-tools:latest
    - name: registry.redhat.io/rhel9/support-tools:latest
