apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-storageclass
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.10.0.1
  share: /shares/openshift
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
